# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # PR for Swift 5.10
      - uses: fwcd/swift-docc-action@v1
        with:
          target: CompoundPredicate
          output: ./Documentation.doccarchive
          hosting-base-path: yourproject
          disable-indexing: 'true'
          transform-for-static-hosting: 'true'
          hosting-base-path: "/CompoundPredicate"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Documentation Archive
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./Documentation.doccarchive/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
